### PR TITLE
Fixed string being evaluated as never type in typescript typeguard

### PR DESCRIPTION
**Pull request by nhinhdao**
- [x] Related GitHub issue(s) linked in PR description
 #82 
- [x] Destination branch merged, built and tested with your changes
- [x] Code formatted and follows best practices and patterns
- [x] Code builds cleanly (no _additional_ warnings or errors)
- [x] Manually tested
- [x] Automated tests are passing
- [x] No _decreases_ in automated test coverage
- [x] Documentation updated (readme, docs, comments, etc.)
- [x] Localization: No hard-coded error messages in code files (_minimally_ in string constants)

### CODE REVIEW

**Comment by brandongregoryscott** [comment]
@nhinhdao I still don't think this is quite right. 

image

If `isEmpty` returns false, we should know that `value` is *not* undefined or null, at least from a typing perspective - and we should _know_, at least from a data perspective, that it is *not* an empty string (ie `""`). I'm going to push up changes to these type guards to support this - I am thinking Rider is not properly detecting the type guards which is why it didn't pick this up in your screenshot on #82

**Comment by nhinhdao** [comment]
My bad, I didn't read it carefully, `value is ''` only applies to `isEmpty`. I am pushing up a change right now.

**Comment by nhinhdao** [comment]
My solution is to use `isEmpty` for the other two methods:

image

However we can also you **non-null assertion operater !** or casting `value as string` inside **hasValue** or **isValidEmail**. What is your thought on this @brandongregoryscott?

**Comment by nhinhdao** [comment]
Actually we don't need to change **hasValue** and **isValidEmail** since the type never issue only occurs when isEmpty returns false, which we already handled

**Comment by brandongregoryscott** [comment]
No problem 👍 I think we're all squared away now. Merging in & publishing 🤞

**Pull request merged**
