### PR TITLE
Support/#15 service utils map paged axios response row count

### LINKED ISSUE #15: ServiceUtils.mapPagedAxiosResponse returns rowCount of current result set, not total result set
Looks like this was lost in translation when porting

`rowCount` on the `ServiceResponse` is being set from `data.resultObject.length` (row count of the currently returned set), when it really should be set off of `data.rowCount` (total result set of the current query) which matches our C# `PagedResult` model:

https://github.com/AndcultureCode/AndcultureCode.JavaScript.Core/blob/master/src/utilities/service-utils.ts#L138
```
    return {
        results: new ResultRecord<TRecord[]>(data),
        resultObjects: resultObjects,
        rowCount: data?.resultObject?.length ?? 0, // should be rowCount: data.rowCount,
        status: axiosResponse.status,
    };
```

https://github.com/AndcultureCode/AndcultureCode.CSharp.Core/blob/master/src/AndcultureCode.CSharp.Core/Models/Errors/PagedResult.cs
```
        public T                          ResultObject   { get; set; }
        public long                       RowCount       { get; set; }
```

I think this transformation method is used for all `list` service calls, whether or not the controller is returning paged results. Maybe it would be best to default it to the current calculated value if `data.rowCount` is null or undefined.

### PR DESCRIPTION
**Pull request by brandongregoryscott**
Fixes #15 

Minor refactor to leverage `CollectionUtils.hasValues` instead of manually null/length checking the returned array.

### CODE REVIEW

**Comment by brandongregoryscott** [comment]
@wintondeshong Not sure how you feel about it, but I was curious: any reason we made the arrays in `ServiceResponse` nullable? (`results` and `resultObjects`) I figure we could default both of them to being empty arrays and reduce the amount of null coalsecing/guarding we have to do on the consumer side? 

Doesn't have to happen now, either way - just figured I would raise the discussion while I'm in here.

**Comment by wintondeshong** [comment]
> @wintondeshong Not sure how you feel about it, but I was curious: any reason we made the arrays in `ServiceResponse` nullable? (`results` and `resultObjects`) I figure we could default both of them to being empty arrays and reduce the amount of null coalsecing/guarding we have to do on the consumer side?
> 
> Doesn't have to happen now, either way - just figured I would raise the discussion while I'm in here.

I can definitely get behind doing that for the array types of `results` and `resultObjects`. Many times I default to not building a habit of allocating objects unnecessarily, but this has a significant impact on developer experience

**Comment by brandongregoryscott** [comment]
@all-contributors add @brandongregoryscott for code, maintenance, test, review

**Comment by brandongregoryscott** [comment]
@all-contributors add @wintondeshong for review

**Pull request merged**
